[package]
name = "intrinsic-triangles"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]

# For the course
ndarray = "0.15"
ndarray-linalg = { version = "0.14", features = ["openblas-system"] }

tobj = "3.2"
